name: flutter_work_ex1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  mask_text_input_formatter: ^2.8.0
  email_validator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Sfprodisplay
      fonts:
        - asset: assets/fonts/SfProDisplay.otf